site_name: DuME Documentation
site_url: http://rainboxlab.org
repo_url: http://dume-docs.rainboxlab.org
edit_uri: https://github.com/Rainbox-dev/DuME/tree/master/src-docs/docs/
site_description: The DuME comprehensive documentation
site_author: Nicolas Dufresne and contributors
copyright: 'Copyright Â© 2019-2020 Rainbox Laboratory and Nicolas Dufresne'
use_directory_urls: false
theme:
    name: readthedocs
    custom_dir: theme/
markdown_extensions:
    - smarty
    - footnotes
    - tables
    - admonition
    - codehilite
    - fenced_code
    - toc:
        permalink: true
extra_css:
    - style.css
    - video.css
extra_javascript:
    - video.js
site_dir: ../docs/
dev_addr: '127.0.0.1:8001'
extra:
    version: '0.1.3'
nav:
    - Home: index.md
    - Installation:
        - Windows: windows.md
        - Mac OS X: mac.md
        - Linux: linux.md
    - Transcoding:
        - Manage presets: presets.md
        - MP4 / h.264: h264.md
        - Image sequences: sequences.md
        - Adding / Changing streams: mapping.md
    - After Effects Rendering:
        - Installation: after-effects-install.md
        - Rendering: after-effects-rendering.md
    - Control and automation:
        - Introduction: api.md
        - Command line options: cli-options.md
        - Server API: server-api.md
    - Changelog: changelog.md
    - License:
        - GNU GPLv3: gnu-gpl.md
        - Documentation license: doc-license.md
    - Contact: https://rainboxlab.org/about/contact/
    - Donate: https://rainboxlab.org/about/donate/
