site_name: DuME Documentation
site_url: http://rainboxlab.org
repo_url: http://dume-docs.rainboxlab.org
edit_uri: https://github.com/Rainbox-dev/DuME/tree/master/src-docs/docs/
site_description: The DuME comprehensive documentation
site_author: Nicolas Dufresne and contributors
copyright: 'Copyright Â© 2019-2020 Rainbox Laboratory and Nicolas Dufresne'
use_directory_urls: false
theme:
    name: readthedocs
    custom_dir: theme/
markdown_extensions:
    - smarty
    - footnotes
    - tables
    - admonition
    - codehilite
    - fenced_code
    - toc
extra_css:
    - style.css
    - video.css
extra_javascript:
    - video.js
site_dir: ../docs/
dev_addr: '127.0.0.1:8001'
extra:
    version: 0.1.0-beta
nav:
    - Home: index.md
    - After Effects Rendering: after-effects.md
    - Changelog: changelog.md
    - License:
        - GNU GPLv3: gnu-gpl.md
        - Documentation license: doc-license.md
    - Contact: https://rainboxlab.org/about/contact/
    - Donate: https://rainboxlab.org/about/donate/
